### ISSUE TITLE
Requirements are not complete

### ISSUE THREAD

**Issue by Cosmopal** [vpn1997/2048-Ai#19]
I had to do a manual install of python-xlib to run the requirements install. Without that the following error came, even if I put python-xlib requirement on top in the file:
`Collecting python-xlib (from -r requirements.txt (line 1))
  Downloading python_xlib-0.20-py2.py3-none-any.whl (119kB)
    100% |████████████████████████████████| 122kB 404kB/s 
Collecting PyAutoGUI==0.9.36 (from -r requirements.txt (line 4))
  Downloading PyAutoGUI-0.9.36.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 1.7MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vZHNvW/PyAutoGUI/setup.py", line 6, in <module>
        version=__import__('pyautogui').__version__,
      File "pyautogui/__init__.py", line 115, in <module>
        from . import _pyautogui_x11 as platformModule
      File "pyautogui/_pyautogui_x11.py", line 7, in <module>
        from Xlib.display import Display
    ImportError: No module named Xlib.display
`

Also, when I ran the code after this, another module came as not installed: `Tkinter`
I guess this is because to install tinker, you have to do apt-get install and not pip install

**Comment by Cosmopal** [comment]
@vpn1997 any reason why specific versions are mentioned for the modules in the requirements?

**Comment by vpn1997** [comment]
These are the minimum requirements for running the game.It wont be a matter if u have higher versions.
Btw tkinter(python2) or Tkinter(python3) comes preinstalled with python.

**Comment by Cosmopal** [comment]
It didn't for me. I have both python2.7 and python3, but, I had to run a manual apt-get install python-tk for the program to run

**Comment by Cosmopal** [comment]
So can I fix this?

**Comment by Cosmopal** [comment]
PR made, pls check

**Comment by vpn1997** [comment]
Guess you are probably right.It was showing same error on another system.Weird nobody got that error before.
