### ISSUE TITLE
Adding score function in the game.

### ISSUE THREAD

**Issue by vpn1997** [vpn1997/2048-Ai#2]
Add score  to every move in the game.

**Comment by andrejristevski** [comment]
I am working on it

**Comment by Emanon42** [comment]
I have sent the pull request. Please tell me what should I do the change in this function.

**Comment by vpn1997** [comment]
Firstly thanks for your contribution.
Things you need to change-
1.  Add try except for tkinter so that it works on both python3x and python2x.
2. Your score function gives the sum of all the tiles present on the board( that's why it starts with some non zero number), but in the original 2048 game your score gets incremented by the sum of tiles that are being merged.

**Comment by Emanon42** [comment]
Done. Anything else?

**Comment by Emanon42** [comment]
I have edited the pull request as your wish. Anything else I can do?

**Comment by vpn1997** [comment]
Looks good. Just make that score tile look different from others, maybe change its background colour etc use your creativity ,otherwise good job.I'll merge after that.

**Comment by Emanon42** [comment]
I have changed the color of font and background of score tile.

**Comment by vpn1997** [comment]
All done now.
