### ISSUE TITLE
Closing button does not works in the output window.

### ISSUE THREAD

**Issue by vpn1997** [vpn1997/2048-Ai#6]
When the program is running and if u try to close the output window manually , it does not work.
Instead you have to close it from the terminal and sometimes you have to close the terminal in order to close the output window.
File - puzzle.py

**Comment by shinning91** [comment]
Will take a look at this

**Comment by vpn1997** [comment]
Cool,waiting for your pull request.

**Comment by vpn1997** [comment]
issue is now resolved
